import { NextRequest, NextResponse } from 'next/server';
import { getRepo, getSql } from '@/lib/db';
import {
  startChapterTranscriptionActor,
  startChapterIngestActor,
  startChapterPlanActor,
} from '@/lib/actor-actions';
import { logger } from '@audiocomic/shared';

const log = logger.scoped('rewind');
export const dynamic = 'force-dynamic';

// POST /api/chapters/[id]/rewind?to=<stage>
//
// Rewinds a chapter to a specific pipeline stage by deleting all data produced
// by that stage and everything after it, then re-triggering from that point.
//
// Stages (in pipeline order):
//   transcribe  — deletes everything, re-runs transcription from scratch
//   ingest      — keeps transcript_chunks, deletes KB + everything after, re-runs ingest
//   plan        — keeps transcript + KB, deletes story/pages/panels + everything after, re-runs plan
//   render      — keeps story/pages/panels, deletes render results + composites + lettering, re-runs render
//
// Query params:
//   to — target stage (one of: transcribe, ingest, plan, render)
export async function POST(
  req: NextRequest,
  { params }: { params: Promise<{ id: string }> },
) {
  const { id: chapterId } = await params;
  const targetStage = req.nextUrl.searchParams.get('to') ?? 'plan';

  const validStages = ['transcribe', 'ingest', 'plan', 'render'] as const;
  if (!validStages.includes(targetStage as (typeof validStages)[number])) {
    return NextResponse.json(
      { error: `Invalid stage "${targetStage}". Valid: ${validStages.join(', ')}` },
      { status: 400 },
    );
  }

  log.info('rewind request', { chapterId, to: targetStage });

  try {
    const repo = await getRepo();
    const sql = await getSql();
    if (!sql) {
      return NextResponse.json({ error: 'Database not available' }, { status: 500 });
    }

    const chapter = await repo.chapters.getById(chapterId);
    if (!chapter) {
      return NextResponse.json({ error: 'Chapter not found' }, { status: 404 });
    }

    const projectId = chapter.projectId;
    const chapterIndex = chapter.index;

    // ── Delete data in reverse pipeline order ──
    // Each stage deletes its own outputs + everything downstream.
    // render: panel render results + requests + panel render_result_id refs
    if (targetStage === 'transcribe' || targetStage === 'ingest' || targetStage === 'plan' || targetStage === 'render') {
      // Clear render_result_id references on panel_specs
      await sql`UPDATE panel_specs SET render_result_id = NULL WHERE chapter_id = ${chapterId}`;
      // Delete render results for panels in this chapter
      await sql`DELETE FROM panel_render_results WHERE panel_id IN (SELECT id FROM panel_specs WHERE chapter_id = ${chapterId})`;
      await sql`DELETE FROM panel_render_requests WHERE panel_id IN (SELECT id FROM panel_specs WHERE chapter_id = ${chapterId})`;
      // Delete export bundles for this chapter (chapterId stored in metadata jsonb)
      await sql`DELETE FROM export_bundles WHERE project_id = ${projectId} AND metadata->>'chapterId' = ${chapterId}`;
    }


    // plan: story_sections, page_specs, panel_specs, character_profiles, world_bibles (from plan)
    if (targetStage === 'transcribe' || targetStage === 'ingest' || targetStage === 'plan') {
      // story_sections has no chapter_id — delete all for this project.
      // They're regenerated by the planner. (Safe for single-chapter projects;
      // for multi-chapter, this would nuke other chapters' sections too.)
      await sql`DELETE FROM story_sections WHERE project_id = ${projectId}`;
      await sql`DELETE FROM panel_specs WHERE chapter_id = ${chapterId}`;
      await sql`DELETE FROM page_specs WHERE chapter_id = ${chapterId}`;
      // character_profiles and world_bibles are project-scoped (not chapter-scoped).
      // They're written by both ingest (wiki) and plan (story planner).
      // We only delete them for full re-transcribe to avoid nuking cross-chapter KB.
    }

    // ingest: knowledge_embeddings, character_states, chapter_ingest_log
    // NOTE: knowledge_pages, character_profiles, world_bibles are project-scoped
    // (no chapter_id). Deleting them on a per-chapter rewind would nuke other
    // chapters' data. They're only cleaned on a full re-transcribe.
    if (targetStage === 'transcribe' || targetStage === 'ingest') {
      await sql`DELETE FROM knowledge_embeddings WHERE chapter_id = ${chapterId}`;
      await sql`DELETE FROM character_states WHERE chapter_id = ${chapterId}`;
      await sql`DELETE FROM chapter_ingest_log WHERE chapter_id = ${chapterId}`;
    }

    // transcribe: transcript_chunks + everything else
    if (targetStage === 'transcribe') {
      await sql`DELETE FROM transcript_chunks WHERE chapter_id = ${chapterId}`;
      await sql`DELETE FROM speaker_turns WHERE project_id = ${projectId}`;
      await sql`DELETE FROM knowledge_pages WHERE project_id = ${projectId}`;
      // Also clean project-scoped KB that plan/ingest wrote
      await sql`DELETE FROM character_profiles WHERE project_id = ${projectId}`;
      await sql`DELETE FROM world_bibles WHERE project_id = ${projectId}`;
      await sql`DELETE FROM scene_profiles WHERE project_id = ${projectId}`;
      await sql`DELETE FROM object_profiles WHERE project_id = ${projectId}`;
    }

    // ── Reset chapter status ──
    const stageMap: Record<string, { status: string; transcriptionStatus: string; stage: string }> = {
      transcribe: { status: 'pending', transcriptionStatus: 'pending', stage: 'pending' },
      ingest: { status: 'transcribed', transcriptionStatus: 'completed', stage: 'ingesting' },
      plan: { status: 'transcribed', transcriptionStatus: 'completed', stage: 'planning' },
      render: { status: 'ready_for_review', transcriptionStatus: 'completed', stage: 'rendering' },
    };
    const reset = stageMap[targetStage]!;
    await repo.chapters.patch(chapterId, {
      status: reset.status,
      transcriptionStatus: reset.transcriptionStatus,
      stage: reset.stage,
      stageProgress: null,
    } as Record<string, unknown>);

    // ── Re-trigger from target stage ──
    let result: unknown;
    if (targetStage === 'transcribe') {
      result = await startChapterTranscriptionActor(chapterId, projectId, chapterIndex);
    } else if (targetStage === 'ingest') {
      result = await startChapterIngestActor(chapterId, projectId, chapterIndex);
    } else if (targetStage === 'plan') {
      result = await startChapterPlanActor(chapterId, projectId, chapterIndex);
    } else if (targetStage === 'render') {
      // Render needs the actor to be in the right state — use SetStage then StartRender
      const { startChapterRenderActor } = await import('@/lib/actor-actions');
      result = await startChapterRenderActor(chapterId);
    }

    log.info('rewind complete', { chapterId, to: targetStage });

    return NextResponse.json({
      chapterId,
      rewoundTo: targetStage,
      message: `Chapter rewound to "${targetStage}" stage and re-triggered.`,
      result,
    });
  } catch (e) {
    const msg = e instanceof Error ? e.message : String(e);
    log.error('rewind failed', { chapterId, error: msg });
    return NextResponse.json({ error: msg }, { status: 500 });
  }
}
